version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: secret-notes-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: secret_note
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  secret-notes-app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: secret_note
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run start:prod

volumes:
  postgres_data:

